title: "CUT&TAG Test Pipeline"
subtitle: "A subtitle to go underneath in grey"
intro_text: "This is the intro text"
report_comment: >
    This is a report summary - TODO: FILL
custom_logo_url: "https://sciencecouncil.org/web/wp-content/uploads/2019/03/CRICK_Logo1.jpg"
custom_logo_title: "The Francis Crick Institute"

report_header_info:
  - Contact E-mail: "chris.cheshire@crick.ac.uk"
  - Application Type: "CUT&TAG"
  - Project Type: "Application"
  - Sequencing Platform: "HiSeq 2500 High Output V4"
  - Sequencing Setup: "2x50"

show_analysis_paths: True
show_analysis_time: True

show_hide_buttons:
  - Read Group 1
  - Read Group 2
  - Controls
  - Conditions
show_hide_mode:
  - show
  - show
  - show
  - show
show_hide_patterns:
  - _r1
  - _r2
  - igg_
  - ["h3k4me3_", "h3k27me3_"]

section_comments:
    fastqc_sequence_counts: "This comment is for a module header, but should still work"

# hg38_genome
# hg38_txome
# mm10_genome
# mm10_txome
fastqc_config:
  fastqc_theoretical_gc: "hg38_genome"

# module_order:
#   - fastqc:
#       name: "FastQC (trimmed)"
#       anchor: "fastqc_trimmed"
#       info: "This section of the report shows FastQC results after adapter trimming."
#       target: ""
#       path_filters:
#         - "*_1_trimmed_fastqc.zip"
#   - cutadapt
#   - fastqc:
#       name: "FastQC (raw)"
#       anchor: "fastqc_raw"
#       path_filters:
#         - "*_1_fastqc.zip"

module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      info: "This section of the report shows FastQC results before adapter trimming."

remove_sections:
  - fastqc_raw_fastqc_per_base_sequence_content