title: "CUT&TAG Test Pipeline"
subtitle: "A subtitle to go underneath in grey"
intro_text: "This is the intro text"
report_comment: >
    This is a report summary - TODO: FILL
custom_logo_url: "https://sciencecouncil.org/web/wp-content/uploads/2019/03/CRICK_Logo1.jpg"
custom_logo_title: "The Francis Crick Institute"

report_header_info:
  - Contact E-mail: "chris.cheshire@crick.ac.uk"
  - Application Type: "CUT&TAG"
  - Project Type: "Application"
  - Sequencing Platform: "HiSeq 2500 High Output V4"
  - Sequencing Setup: "2x50"

show_analysis_paths: True
show_analysis_time: True

show_hide_buttons:
  - Read Group 1
  - Read Group 2
  - Controls
  - Conditions
show_hide_mode:
  - show
  - show
  - show
  - show
show_hide_patterns:
  - _r1
  - _r2
  - igg_
  - ["h3k4me3_", "h3k27me3_"]

section_comments:
    fastqc_raw_fastqc_per_base_sequence_content: >
        The discordant sequence content at the begining of the reads are common phenomenon for CUT&Tag reads. Failing to pass the Per base seuqnence content does not mean your data failed.
        - It can be due to the Tn5 preference.
        - What you might be detecting is the 10-bp periodicity that shows up as a sawtooth pattern in the length distribution. If so, this is normal and will not affect alignment or peak calling. In any case we do not recommend trimming as the bowtie2 parameters that we list will give accurate mapping information without trimming.

# hg38_genome
# hg38_txome
# mm10_genome
# mm10_txome
fastqc_config:
  fastqc_theoretical_gc: "hg38_genome"

# Run only these modules
run_modules:
    - fastqc
    - cutadapt
    - bowtie2

# module_order:
#   - fastqc:
#       name: "FastQC (trimmed)"
#       anchor: "fastqc_trimmed"
#       info: "This section of the report shows FastQC results after adapter trimming."
#       target: ""
#       path_filters:
#         - "*_1_trimmed_fastqc.zip"
#   - cutadapt
#   - fastqc:
#       name: "FastQC (raw)"
#       anchor: "fastqc_raw"
#       path_filters:
#         - "*_1_fastqc.zip"

module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      info: "This section of the report shows FastQC results before adapter trimming."
      path_filters:
        - "*_r*_fastqc.zip"
  - cutadapt
  - fastqc:
      name: 'FastQC (trimmed)'
      info: 'This section of the report shows FastQC results after adapter trimming.'
      path_filters:
         - "*_trimmed*_fastqc.zip"
  - bowtie2:
      name: 'Bowtie2 (target)'
      path_filters:
         - "*exp*_stats.txt"
  - bowtie2:
      name: 'Bowtie2 (spike-in)'
      path_filters:
         - "*spike_in*_stats.txt"

#remove_sections:
#  - fastqc_raw_fastqc_per_base_sequence_content


# Customise the module search patterns to speed up execution time
#  - Skip module sub-tools that we are not interested in
#  - Replace file-content searching with filename pattern searching
#  - Don't add anything that is the same as the MultiQC default
# See https://multiqc.info/docs/#optimise-file-search-patterns for details
sp:
    cutadapt:
        fn: '*trimming_report.txt'



    # samtools/stats:
    #     fn: '*.stats'
    # samtools/flagstat:
    #     fn: '*.flagstat'
    # samtools/idxstats:
    #     fn: '*.idxstats*'

    # rseqc/bam_stat:
    #     fn: '*.bam_stat.txt'
    # rseqc/gene_body_coverage:
    #     skip: true
    # rseqc/junction_annotation:
    #     fn: '*.junction_annotation.log'
    # rseqc/read_gc:
    #     skip: true
    # rseqc/read_distribution:
    #     fn: '*.read_distribution.txt'
    # rseqc/infer_experiment:
    #     fn: '*.infer_experiment.txt'

    # picard/markdups:
    #     fn: '*.MarkDuplicates.metrics.txt'
    # picard/alignment_metrics:
    #     skip: true
    # picard/basedistributionbycycle:
    #     skip: true
    # picard/gcbias:
    #     skip: true
    # picard/hsmetrics:
    #     skip: true
    # picard/insertsize:
    #     skip: true
    # picard/oxogmetrics:
    #     skip: true
    # picard/pcr_metrics:
    #     skip: true
    # picard/quality_by_cycle:
    #     skip: true
    # picard/quality_score_distribution:
    #     skip: true
    # picard/quality_yield_metrics:
    #     skip: true
    # picard/rnaseqmetrics:
    #     skip: true
    # picard/rrbs_metrics:
    #     skip: true
    # picard/sam_file_validation:
    #     skip: true
    # picard/variant_calling_metrics:
    #     skip: true
    # picard/wgs_metrics:
    #     skip: true